# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Code vulnerability scanning
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: "${{ github.workspace }}"
        fail-build: false
        severity-cutoff: high

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
